[package]
name = "database-monitor"
version = "0.1.0"
authors = ["Shabanov Anton"]

[dependencies]
argparse = "0.2"
env_logger = "0.5"
iron = "0.6"
log = "0.4"
mount = "0.4"
postgres = "0.15"
router = "0.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
staticfile = "0.5"
time = "0.1"
