[package]
name = "database-monitor"
version = "0.1.0"
authors = ["snake"]

[dependencies]
argparse = "0.2"

env_logger = "0.3"
log = "0.3"
postgres = "0.13"
rustc-serialize = "0.3"
time = "0.1"
iron = "0.4"
staticfile = "0.3"
mount = "0.2"
router = "0.4"
# handlebars-iron = "0.22"
