[package]
name = "database-monitor"
version = "0.1.0"
authors = ["snake"]

[dependencies]
argparse = "0.2"
env_logger = "0.3"
iron = "0.4"
log = "0.3"
mount = "0.2"
postgres = "0.13"
router = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
staticfile = "0.3"
time = "0.1"
